### ISSUE TITLE
GLPK and installation of sdcTable 0.22.7

### ISSUE THREAD

**Issue by junoslukan** [bernhard-da/sdcTable#36]
While trying to update sdcTable from version 0.22.6 to 0.22.7, I get the following error:

```
csp.cpp:2:18: fatal error: glpk.h: No such file or directory
 #include <glpk.h>
                  ^
compilation terminated.
make: *** [csp.o] Error 1
```

and further below

```
ERROR: package installation failed
Installation failed: Command failed (1)
```

This happens regardless of whether I try to update the package via CRAN (as in `install.packages("sdcTable")`) or via GitHub (by using `devtools::install_github("bernhard-da/sdcTable", build_vignettes=TRUE)`).

I have the package `Rglpk` installed and updated and I'm using the latest version of R and RStudio on a Windows 7 64-bit machine.

I [noticed](https://cran.r-project.org/web//packages/sdcTable/) the 

> SystemRequirements: GLPK library, including -dev or -devel part

but I'm not sure how to use this piece of information.

**Comment by bernhard-da** [comment]
hi @junoslukan,

the easiest way is to wait a few hours until the new version of sdcTable is available also for windows on CRAN so that you can just do `update.packages()` or `install.packages("sdcTable")`.

**Comment by bernhard-da** [comment]
it's probably enough to install glpk from [**here**](http://winglpk.sourceforge.net/), though.

**Comment by junoslukan** [comment]
Hi @bernhard-da,

Thank you for your quick reply! It seems that I was too eager to update sdcTable. I can wait until the package binaries are available on CRAN, of course.

Thank you again.
