### ISSUE TITLE
Can't run TauArgus batch file from R with <freq> rule

### ISSUE THREAD

**Issue by jj585** [bernhard-da/sdcTable#37]
Running TauArgus batch file with runArgusBatchFile() function when frequency rule is applied does not seem to work.
From the log file I conclude that the procedure stops at READMICRODATA phase, however I can read micro-data and metadata files prepared with createArgusInput() function from R in TauArgus manually.

Full R script of the problem in the test.txt file (example is similar to the the example in sdcTable manual on page 19/20/21 except without responsevar="num1" parameter).

![console](https://user-images.githubusercontent.com/24804698/36142022-87cff400-10af-11e8-8b48-5c677608e98b.png)
[test.txt](https://github.com/bernhard-da/sdcTable/files/1719320/test.txt)

**Comment by bernhard-da** [comment]
hi @jj585, thx for reporting this. i can indeed reproduce the issue and I have not yet a clue what is the problem. i've asked @ppdewolf the maintainer of tau-argus [**here**](https://github.com/sdcTools/UserSupport/issues/86) for this opinion.

**Comment by bernhard-da** [comment]
hi @jj585 , as explained [**here**](https://github.com/sdcTools/UserSupport/issues/86), this is a bug in tau-argus that will be fixed in the next version.

**Comment by jj585** [comment]
thx for the support provided @bernhard-da !
