### ISSUE TITLE
How to define hierarchy correctly

### ISSUE THREAD

**Issue by jj585** [bernhard-da/sdcTable#38]
It is not an issue actually, but it is more a question how to!

I have a problem with specifying hierarchy for a variable properly for sdcTable (and also TauArgus).

If I have a variable 'region' (with values A, B and C) and I want to include in the table cells A, B and C and also their total 'A+B+C' it can be done easily:
dim.region <- data.frame(levels=c('@','@@','@@','@@'), codes=c('A+B+C', 'A','B','C'),

But I do not understand how to define hierarchy correctly if I need to include in the output also groups A+B, A+C and B+C. ?

dim.region <- data.frame(levels=c('@','@@','@@@','@@@','@@'), codes=c('A+B+C', 'A + B', 'A', 'B', 'C'),

What to do in this case if I need to protect a table with cells A, B, C, A+B, A+C and B+C and A+B+C?
Do I need to define three separate hierarchies

dim.region1 <- data.frame(levels=c('@','@@','@@@','@@@','@@'), codes=c('A+B+C', 'A+B', 'A', 'B', 'C'),
dim.region2 <- data.frame(levels=c('@','@@','@@@','@@@','@@'), codes=c('A+B+C', 'A+C', 'A', 'C', 'B'),
dim.region3 <- data.frame(levels=c('@','@@','@@@','@@@','@@'), codes=c('A+B+C', 'B+C', 'B', 'C', 'A'),

and then protect these table as linked tables or there is another/ better way ?

**Comment by bernhard-da** [comment]
hi @jj585 you always have a problem if you have a structure like the one in your example where some codes (lowest level) are contribution to more than 1 subtotal. 

so I'd say this needs to be considered using a "linked-table" approach as the three dimensions obviously have some common cells. I'm afraid there is no "simple" solution to that.

**Comment by jj585** [comment]
Thanks a lot @bernhard-da !
